name: End-to-end tests 🧪
on:
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install dependencies
        run: |
          npm install

      - name: Load environment variables
        uses: actions/checkout@v2
        with:
          path: .github/workflows/env.yml

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          config-file: cypress.config.js
